title: NoxInmortus Blog
author: ""
email: me [at] noxinmortus.fr
description: >-
  Réflexions sur divers sujets techniques, écologiques et éthiques.
url: "https://noxinmortus.github.io"
github_username: NoxInmortus
timezone: Europe/Paris
encoding: "utf-8"

theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 8
paginate_path: /page:num/
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CHANGELOG.md
  - LICENSE
  - CNAME
